### ISSUE TITLE
Crashes on Windows 2012 R2

### ISSUE THREAD

**Issue by CaledoniaProject** [securifera/serviceFu#5]
Hello there,

Have you tried to run on Windows 2012 R2 Domain controller? I got a crash ... 

![screen 2018-10-13 at 11 20 02](https://user-images.githubusercontent.com/1357701/46900771-298b7d80-ceda-11e8-9011-f627988dc544.jpg)

**Comment by securifera** [comment]
Since it looks like you compiled it on the same machine, have you tried debugging it to see where it's crashing?
